GET http://127.0.0.1:8000/user/by_email?email=leal@outlook.com HTTP/1.1

###

GET http://127.0.0.1:8000/user/by_id?id=2 HTTP/1.1

###

POST http://127.0.0.1:8000/user HTTP/1.1
content-type: application/json

{
  "fullname": "Leal",
  "email": "leal@outlook.com",
  "password": "123456"
}

###

PUT http://127.0.0.1:8000/user HTTP/1.1
content-type: application/json

{
  "id": 5,
  "email": "leal@outlook.com",
  "fullname": "Leal Nalbert"
}